### ISSUE TITLE
Monitoring multiple bosh directors

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry-community/prometheus-boshrelease#106]
Is it possible to monitor multiple bosh directors with a single prometheus deployment? We would like to run a single prometheus that collects metrics from multiple directors (staging and production). It looks like the bosh exporter only talks to a single director, so we'd need to run multiple instances of the exporter. And that would mean running each exporter on a separate vm, since bosh doesn't know how to run multiple instances of the same job on the same host. And that would mean prometheus wouldn't be able to read service discovery files generated by bosh exporters, since we can only colocate prometheus with one of the exporters.

It seems like our options for this use case would be:
* Teach the bosh exporter to monitor multiple bosh directors
* Run multiple vms, each with prometheus and bosh exporter, and use federation to combine metrics

Does the first option make sense to you @frodenas, or do you think the exporter should only monitor a single director? Or am I missing a simpler solution?

cc @cnelson

**Comment by cppforlife** [comment]
> And that would mean running each exporter on a separate vm, since bosh
doesn't know how to run multiple instances of the same job on the same host.

i was just chatting with @dpb587 about plans for this in the future...

> And that would mean prometheus wouldn't be able to read service discovery
files generated by bosh exporters

what are "service discovery files" that bosh exporter generates?

**Comment by frodenas** [comment]
@jmcarp I've heard this request several times, and not only for the `bosh_exporter`, but for other exporters as well.

The best practice recommended by the prometheus developers has always been an exporter should monitor a single resource and spin up as many instances of the exporter as resources to monitor (and if possible collocated with the resource to be monitored). This is why most (if not all) of the exporters only support scrapping a single resource. This is a challenge when using bosh (and you already mentioned why), and specifically, it's more challenging for the `bosh_exporter`, as it needs to be collocated with the prometheus server in order to use the service discovery approach. 

I've used the 2nd approach multiple times (multiple prometheus and use federation), and this is the pattern that I recommend. I known that this might be overkilling, but I'm reluctant to apply the 1st approach (update the `bosh_exporter` to allow scrapping multiple directors) because:

1. I want to follow the common approach of scrapping a single resource; 
2. I want to find a solution that can be applied to all exporters.

One option that I've been considering is to use the pattern used by the [docker-boshrelease](https://github.com/cloudfoundry-community/docker-boshrelease/blob/master/jobs/containers/monit#L1) (and maybe use it alongside the *alpha* [bpm](https://github.com/cloudfoundry-incubator/bpm-release)). This will allow to spin up multiple instances of the same exporter using a single job (and therefore, in the same vm) and running as a separate isolated processes (for those exporters that use env vars for configuration). For example, the `bosh_exporter` job can accept an array of properties and it can dynamically invoke separate `bosh_exporter` processes using bpm. Each process will write the service discovery file using a different name, and prometheus can scrape all of them. Obviously, I'm over simplifying the solution (still need to spike on it), but it might be worth a try.

**Comment by frodenas** [comment]
@cppforlife Any hints about those *future plans*?

The service discovery file contains all vm's IP addresses and some metadata (like the `job` and `processes` running on each vm). The format of that file is described at the prometheus [documentation](https://github.com/prometheus/prometheus/tree/master/discovery#writing-an-sd-mechanism). It's super useful when you don't know up front which will be the IP addresses (b/c bosh will handle that or b/c you've deployed an addon). Instead of configuring prometheus with the IP addresses of the exporters to be scrapped, it reads the configuration from a service discovery file and applies some logic to determine the exporter (an example can be found at this [operator file](https://github.com/cloudfoundry-community/prometheus-boshrelease/blob/master/manifests/operators/monitor-bosh.yml#L50)).

**Comment by cppforlife** [comment]
we were thinking about automatically setting <% spec.name %> to job+guid
(that director generates) and having release author use spec.name in paths
and monit names. it a fairly cheap change i think compared alternatives.
wdyt?

**Comment by frodenas** [comment]
what happens with properties? Will all instances share the same properties?

**Comment by frodenas** [comment]
related to https://github.com/cloudfoundry-community/prometheus-boshrelease/issues/11

**Comment by jriguera** [comment]
We are also facing this issue. We think the best approach is using prometheus federation.

But, what about writing a SD discovery module for BOSH: https://github.com/prometheus/prometheus/tree/master/discovery ? 

With the director  HTTP API is easy to get the list of VMs and the metadata to provide the deployments name, etc.

**Comment by frodenas** [comment]
@jriguera The [bosh_exporter](https://github.com/cloudfoundry-community/bosh_exporter) already implements a [sd collector](https://github.com/cloudfoundry-community/bosh_exporter#service-discovery). You can also see it in action when using the [bosh op file](https://github.com/cloudfoundry-community/prometheus-boshrelease/blob/master/manifests/operators/monitor-bosh.yml#L50).

**Comment by jriguera** [comment]
Yep, true (Sorry, Its Monday ....) I was thinking on the prometheus side, what I wanted to say is implementing a `bosh_sd_config` on their side in the same way there is a `kubernetes_sd_config` which talks directly with the API, but ofc, it has to be done in the Prometheus project.

**Comment by frodenas** [comment]
Prometheus devs don't easily accept new sds, there has been some pushback recently when some ppl tried to implement sd into prometheus. But up to you if you want to propose it at the prometheus github repo 😄

**Comment by frodenas** [comment]
@jmcarp Please reopen if you still have more doubts about the recommended approach.
