### ISSUE TITLE
multiple bosh exporters / exporter authent

### ISSUE THREAD

**Issue by poblin-orange** [cloudfoundry-community/prometheus-boshrelease#11]
Hello, i have complex deployment, incuding multiple bosh director.
I understand i can configure different ports for multiple exporters. However i cant see how to configure multiple exporters in the same vm/instance group.

Do i have to configure separate vm/instance group per bosh exporter ?
In that case, is it possible to secure prometheus => bosh exporter link (basic auth, ssl ?)
Could bosh-links help wiring multiple bosh exporter to prometheus server transparently  ?

thx
Pierre

BTW: fantastic job on this bosh release!  Really nice out of the box grafana / prometheus / alerting experience out of the box !

**Comment by frodenas** [comment]
@poblin-orange, thanks for dropping by and testing this release!

The [bosh exporter](https://github.com/cloudfoundry-community/bosh_exporter) is a job template, that means it can be only deployed once per vm. Same happens with other exporters, you can only deploy once of the same type per vm (ie, you cannot have two mysql_exporter in the same vm, but you can have 1 bosh_exporter and 1 mysql_exporter collocated). Also, the bosh exporter only supports a single director configuration, so if you want to target more than 1 director you'll need to deploy a bosh exporter per director on different vms.

Bosh links will not help here because they only support a single producer job. So in order to have just one producer, we will need to collocate different exporters with different configurations in the same vm, and as I mentioned before, that's not possible. Also, even if we can configure 2 vms with the bosh_exporter, bosh links only supports a single link, so only one of them can be the producer. 

There are alternative approaches to solve this problem, like the prometheus service discovery. The bosh exporter already [supports this](https://github.com/cloudfoundry-community/bosh_exporter/blob/master/FAQ.md#how-can-i-use-the-service-discovery), and it's useful not only to get bosh metrics but also to configure dynamically the scrappe jobs without requiring modifying the prometheus deployment every time you add a new node (ie, specially usefull when you deploy the [node_exporter](https://github.com/prometheus/node_exporter) as part of the bosh [runtime-config](http://bosh.io/docs/runtime-config.html)).

w/r/t security, what's your use case? We typically secure access to the prometheus console and grafana, but not between prometheus and the exporters (albeit there're a few exporters that support that configuration).

When scrapping for bosh metrics from 2 different bosh directors you've 2 options:
1. If you are not using the service discovery approach, then you can use a single prometheus server and configure 2 scrape targets (1 per bosh exporter). In this case, I recommend collocating the bosh_exporter within the bosh director vm, and then configure the prometheus server like this:

  ```yaml
  properties:
    prometheus:
      scrape_configs:
        - job_name: bosh
          scrape_interval: 1m
          scrape_timeout: 1m
          static_configs:
            - targets:
              - <bosh exporter 1 IP address>:9190
              - <bosh exporter 2 IP address>:9190
  ```

2. If you want to use the service discovery approach, things became a bit tricky, because the service discovery file must be located at the prometheus server vm. In this case, as you cannot have 2 bosh exporters at the same prometheus server vm, my recommendation is to use 2 different prometheus servers, each one scrapping metrics from a single bosh director and associated bosh deployments, and then having a 3rd prometheus server that federates metrics from the 2 previous prometheus servers. This is also my recommendation when dealing with big deployments (usually involving more than 1 AZ).

It's on my [icebox](https://github.com/cloudfoundry-community/prometheus-boshrelease/issues/2) to create some useful documentation on how to deploy this release and how to monitor bosh deployments (including CF platform and CF applications). In the meantime, please check this **draft** diagram about an example [HA deployment topology](https://github.com/cloudfoundry-community/prometheus-boshrelease/blob/master/docs/Deployment%20Topology.svg). 

Also, I'd love to spend some time with you to hear your specific use cases, and may be giving some recommendations and examples on how to deploy this bosh release. Please ping me if you're interested, I'll be glad to help you.

**Comment by poblin-orange** [comment]
@frodenas Thanks for quick and clear explanation.
Ill have a look at the discovery feature, seems very powerfull with node-exporter.

My security concern is, as you mentionned, the exporter http endpoint, specially when dispatched on remote vm.

Looking at the prometheus [doc](https://prometheus.io/docs/operating/configuration/#scrape_config), scrape-configs enables prometheus to consume basic-auth / TLS metrics endpoints

So i think the issue is per exporter as you mentionned. Could use an haproxy job to secure this endpoint though, ill give it try.

I like the idea of cascading prometheus metrics server. This would match our current topology (we cascade bosh directors micro => master => per zone bosh directors ...).

My colleague @gberche-orange also had some uses cases for prometheus. We 'd be glad to discuss
Thanks
Pierre

**Comment by frodenas** [comment]
@poblin-orange As discussed last Friday:

1. All official Prometheus exporters don't implement authentication. Providing basic-auth and/or TLS is something that can be archived using an haproxy or nginx in front of the exporter. 

2. The cascading prometheus server is something that I'm already testing on a real environment. I'll write proper documentation when I finish my tests.
