### ISSUE TITLE
dup-ed grafana

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry-community/prometheus-boshrelease#31]
It would be great if all just have one grafana realease (like https://github.com/vito/grafana-boshrelease). May be @vito can donate it to cf community if we promise to keep it nice and tidy.

**Comment by frodenas** [comment]
I want to maintain the `grafana` job in this release instead of using a third-party release, and there are two main reasons:

1) The `grafana` job in this release is highly coupled to the `prometheus` job to simplify its configuration (see some of the `prometheus-*` scripts at the [grafana/templates/bin](https://github.com/cloudfoundry-community/prometheus-boshrelease/tree/master/jobs/grafana/templates/bin) directory). Decoupling them will make it harder for users to deploy them.

2) I'm a strong believer in the self-contained, reproducible and consistent aspect of Bosh, and having a separate release doesn't fulfill those requirements, for example, the user must track two different releases, must check that the release versions are compatible, ...

Obviously, you can fulfill the above requirements by using a separate deployment tool alongside Bosh, like using generation scripts, [genesis](https://github.com/starkandwayne/genesis), or all the `*-deployment` experiments that are outside there, but I haven't seen yet a consensus around those tools.
