### ISSUE TITLE
"No data points" when viewing Apps dashboards 

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry-community/prometheus-boshrelease#64]
Been wanting to kick the tires on Prometheus for a while and this release got it up and going super quickly! The only issue I'm having is the Apps dashboards don't display any info (firehose and bosh dashboards are fine). Here's my config, a cf-deployment ops file: https://github.com/cloudfoundry/capi-ci/blob/master/cf-deployment-operations/add-prometheus.yml.

Looks like the `cf_exporter` is in charge of generating metrics for the Apps dashboards. Even when changing the debug level for the exporter job, the only log line is `level=info msg="Listening on :9193" source="cf_exporter.go:278"`. The expected metrics, like "cf_total_application_events" also don't appear in the Prometheus metrics explorer.

Appreciate the help and thanks for building this release!

**Comment by frodenas** [comment]
@ljfranklin There seem to be 2 different issues here (or might be related problems):

1) The `cf_exporter` only gathers administrative info (like app, org, space names, ...). The application metrics showed at the Apps dashboard come from the `HttpStartStop` events from the `firehose_exporter`, and then are merged with the `cf_exporter` metrics in order to show the `names` instead of the`uuid`. But let's focus on the `cf_application_events_total`. The first thing to check is if the `cf_exporter` is really gathering those metrics or not. You can curl the `http://<cf_exporter_vm_ip>:9193/metrics` and check what metrics are exported. If you don't see that metric, check the `cf_last_application_events_scrape_error`, if it's value is `1` then that would mean the exporter was unable to gather those metrics (but theoretically an error message should appear at the `cf_exporter` log files). If you don't see any error, another possible cause is the `authorities` of the `client`, I've seen some erratic behavior when using `cloud_controller.admin_read_only`, so worth trying `cloud_controller.admin` and see if then you get those metrics.

2) w/r/t the *No data points*,  there might be 2 problems. If the Apps dashboard filters don't show you any org, space or app that means we have a problem in 1). If they show you those filters, then the problem might be that the apps doesn't get any traffic. The `HttpStartStop` events are generated by the `gorouter` only when there's a request, otherwise the metrics are not emmited. Can you please generate some traffic to one of the apps and check if the dashboard then emits some metrics?

**Comment by ljfranklin** [comment]
So curling `http://<cf_exporter_vm_ip>:9193/metrics` does return metrics...but only after about 1 minute. Doubling my scrape interval to 2 minutes fixed everything up. Treating the symptoms rather than the cause, I'll try to look into why those calls are so slow. Not sure if this speed is typical or our env is underpowered.

Closing this out, thanks!

**Comment by frodenas** [comment]
@ljfranklin The `Application Events` collector might be involved. I tend to disable it when targeting a medium/big Cloud Foundry environment. The rest of collectors should return the info in less than 1 minute (usually it only takes milliseconds).
